import {Store} from './store';

export const Ldlc: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.stock',
      text: ['stock'],
    },
    maxPrice: {
      container: '.price .price',
      euroFormat: true,
    },
    outOfStock: {
      container: '.stock',
      text: ['rupture'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00317660.html',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00384198.html',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00384225.html',
    },
    {
      brand: 'asus',
      model: 'strix oc white',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00401655.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386907.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386904.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386926.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386925.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386030.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386928.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386927.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385465.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385466.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385462.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385463.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385044.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00400752.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00383549.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00384189.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385043.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386014.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386023.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385663.html',
    },
    {
      brand: 'kfa2',
      model: 'ko',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00393364.html',
    },
    {
      brand: 'kfa2',
      model: 'ex',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00393363.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385048.html',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00408781.html',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00395874.html',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391681.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00408869.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385046.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00408780.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385045.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385128.html',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385129.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385126.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385127.html',
    },
    {
      brand: 'palit',
      model: 'jetstream',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385131.html',
    },
    {
      brand: 'palit',
      model: 'jetstream oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385132.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00401469.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00383541.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc white',
      series: '3070',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398664.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369303.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369299.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369299.html',
    },
    {
      brand: 'msi',
      model: 'gaming z trio',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00423532.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369299.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369072.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00400753.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376208.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368690.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369094.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369150.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369298.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386334.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00396037.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375625.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368844.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368506.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390466.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368789.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398370.html',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391682.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376207.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368691.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369158.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386063.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369268.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391624.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398046.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368931.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375448.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375431.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369265.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390727.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398045.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368692.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368579.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375644.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385535.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386332.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398373.html',
    },
  ],
  name: 'ldlc',
};
